### ISSUE TITLE
Python 3 Support help needed.

### ISSUE THREAD

**Issue by BTopbas** [i96751414/plugin.video.flix#2]
I am able to run Torrest addon on Kodi Matrix with small modifications. But I tried to run Flix on Matrix but no success. 
All modules are compatible with Matrix exclude script.module.futures. I can't found the Python 3 version of this module. Matrix has [script.module.future](https://mirrors.kodi.tv/addons/matrix/script.module.future/) but this addon using [futures](https://mirrors.kodi.tv/addons/leia/script.module.futures/). I think it is not the same module. Because I change futures to future but no success. 

So we need python 3 version of script.module.futures right?

**Comment by i96751414** [comment]
[Futures](https://docs.python.org/3/library/concurrent.futures.html) is part of python3 (3.2+) so it should not require any extra addon I think.

**Comment by BTopbas** [comment]
Okey. I removed futures line. Installed other modules. And addon installed on Matrix! But when run addon error happened.

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : 
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: module 'sys' has no attribute 'maxint'
Traceback (most recent call last):
File "/private/var/mobile/Containers/Data/Application/809DC563-7035-4EB0-A5B6-E6A0208775A2/Library/Caches/Kodi/addons/plugin.video.flix/navigation.py", line 4, in <module>
from lib.navigation import run
File "/private/var/mobile/Containers/Data/Application/809DC563-7035-4EB0-A5B6-E6A0208775A2/Library/Caches/Kodi/addons/plugin.video.flix/lib/navigation.py", line 16, in <module>
from lib.providers import play_search, play_movie, play_show, play_season, play_episode
File "/private/var/mobile/Containers/Data/Application/809DC563-7035-4EB0-A5B6-E6A0208775A2/Library/Caches/Kodi/addons/plugin.video.flix/lib/providers.py", line 10, in <module>
from lib.dialog_select import dialog_select
File "/private/var/mobile/Containers/Data/Application/809DC563-7035-4EB0-A5B6-E6A0208775A2/Library/Caches/Kodi/addons/plugin.video.flix/lib/dialog_select.py", line 13, in <module>
class DialogSelect(WindowXMLDialog):
File "/private/var/mobile/Containers/Data/Application/809DC563-7035-4EB0-A5B6-E6A0208775A2/Library/Caches/Kodi/addons/plugin.video.flix/lib/dialog_select.py", line 34, in DialogSelect
def addItem(self, item, position=sys.maxint):
AttributeError: module 'sys' has no attribute 'maxint'
-->End of Python script error report<--
```
Edit: In python 3 sys.maxint method changed to sys.maxsize now I will try to fix it.
Edit2: Change worked. Addon installs and opens with no problem.

**Comment by i96751414** [comment]
Thanks for that! I've updated the code to use `maxsize` instead.

**Comment by BTopbas** [comment]
But remember I am using with Kodi Matrix and Pyhton3. So this change is only needed for Pyhton3. Maybe maxsize not work with python 2 and current stable Kodi(Leia).

**Comment by i96751414** [comment]
No worries, it exists in py2 and will not break anything
